filter:
    excluded_paths:
        - 'app/*'
        - 'bin/*'
        - '*.min.js'
        - 'web/assets/vendor/*'
        - 'var/'

tools:
    php_cs_fixer: true
    php_mess_detector: true
    php_cpd: true
    sensiolabs_security_checker: true
    php_pdepend: true
    php_code_coverage: false

checks:
    php: true
    javascript: true
