Ivan1986DebBundle:
    resource: "@Ivan1986DebBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_admin_reset:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin

fos_user:
    resource: '@FOSUserBundle/Resources/config/routing/all.xml'
    prefix: /

api_repos:
    type:     rest
    resource:  Ivan1986\DebBundle\Controller\ApiController

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

sonata_user_profile_show:
    path:  /
    defaults: { _controller: Ivan1986DebBundle:Default:Index }
