<?php

namespace Ivan1986\DebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GpgKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GpgKeyRepository extends EntityRepository
{

}
