<?php

namespace Ivan1986\DebBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Anchovy\CURLBundle\CURL\Curl;
use Ivan1986\DebBundle\Exception\GpgNotFoundException;
use Ivan1986\DebBundle\Entity\GpgKey;

/**
 * GpgKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GpgKeyRepository extends EntityRepository
{

}