<?php

namespace Ivan1986\DebBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Ivan1986\DebBundle\Entity\SysPackage;

/**
 * PackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackageRepository extends EntityRepository
{

    /**
     * @return SysPackage|null
     */
    public function getSystem()
    {
        return $this->_em->createQuery('SELECT p FROM Ivan1986\DebBundle\Entity\SysPackage AS p WHERE p.user IS NULL')->getOneOrNullResult();
    }

    /**
     * Список пакетов основного репозитория
     * @return Package[]
     */
    public function mainRepo()
    {
        $data = $this->_em->createQuery('SELECT p FROM Ivan1986\DebBundle\Entity\Package AS p
            WHERE NOT p INSTANCE OF Ivan1986\DebBundle\Entity\SysPackage')->getResult();
        $data[] = $this->getSystem();
        return $data;
    }

}