<?php

namespace Ivan1986\DebBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Ivan1986\DebBundle\Entity\SysPackage;

/**
 * PackageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackageRepository extends EntityRepository
{

    /**
     * @return SysPackage|null
     */
    public function getSystem()
    {
        return $this->createQueryBuilder('p')->where('p INSTANCE OF Ivan1986\DebBundle\Entity\SysPackage')->andWhere('p.user IS NULL')->getQuery()->getOneOrNullResult();
    }

}