<?php

namespace Ivan1986\DebBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Ivan1986\UserBundle\Entity\User;

use Ivan1986\DebBundle\Exception\ParseRepoStringException;

/**
 * RepositoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepositoryRepository extends EntityRepository
{

    /**
     * Получить репозитории пользователя
     *
     * @param User $user
     * @return array
     */
    public function getByUser(User $user)
    {
        return $this->findBy(array('owner' => $user->getId()));
    }

    /**
     * Получить репозиторий по ID с проверкой пользователя
     *
     * @param $id ID репозитория
     * @param User $user пользователь
     * @return object
     */
    public function getByIdAndCheckUser($id, User $user)
    {
        return $this->findOneBy(array('id' => $id, 'owner' => $user->getId()));
    }


}