<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120616192431 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP INDEX UNIQ_13A3541D999517A ON Repository");
        $this->addSql("ALTER TABLE Repository ADD `repoString` VARCHAR(255) NOT NULL, DROP url, DROP `release`, DROP components");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_13A3541D999517A ON Repository (`name`)");
        $this->addSql("ALTER TABLE users CHANGE facebook_data facebook_data LONGTEXT DEFAULT NULL, CHANGE twitter_data twitter_data LONGTEXT DEFAULT NULL, CHANGE gplus_data gplus_data LONGTEXT DEFAULT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP INDEX UNIQ_13A3541D999517A ON Repository");
        $this->addSql("ALTER TABLE Repository ADD components LONGTEXT NOT NULL COMMENT '(DC2Type:array)', CHANGE repostring `release` VARCHAR(255) NOT NULL");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_13A3541D999517A ON Repository (name)");
        $this->addSql("ALTER TABLE users CHANGE facebook_data facebook_data LONGTEXT DEFAULT NULL, CHANGE twitter_data twitter_data LONGTEXT DEFAULT NULL, CHANGE gplus_data gplus_data LONGTEXT DEFAULT NULL");
    }
}
