<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120420100519 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql');

        $this->addSql("ALTER TABLE Repository ADD `release` VARCHAR(255) NOT NULL, ADD components LONGTEXT NOT NULL COMMENT '(DC2Type:array)', ADD bin TINYINT(1) NOT NULL, ADD src TINYINT(1) NOT NULL, ADD name VARCHAR(150) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql');

        $this->addSql('ALTER TABLE Repository DROP `release`, DROP components, DROP bin, DROP src, DROP name');
    }
}
