<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120616192431 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql');

        $this->addSql('ALTER TABLE Repository ADD `repoString` VARCHAR(255) NOT NULL, DROP url, DROP `release`, DROP components');
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql');

        $this->addSql("ALTER TABLE Repository ADD components LONGTEXT NOT NULL COMMENT '(DC2Type:array)', CHANGE repostring `release` VARCHAR(255) NOT NULL");
    }
}
