<?php

namespace Ivan1986\DebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GroupsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupsRepository extends EntityRepository
{
}
