<?php

namespace Ivan1986\DebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getInactive()
    {
        return $this->createQueryBuilder('u')
            ->leftJoin('u.repositories', 'r')
            ->where('u.updatedAt < :date')->setParameter('date', new \DateTime('1 year ago'))
            ->addGroupBy('u')
            ->having('count(r) = 0')
            ->getQuery();
    }

    public function count()
    {
        return $this->createQueryBuilder('r')
            ->select('COUNT(r)')->getQuery()->getSingleScalarResult();
    }
}
